# Generated by Django 5.1.2 on 2024-10-19 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_initial'),
        ('inventory', '0003_delete_fingerprinthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executionhistory',
            old_name='date',
            new_name='execution_date',
        ),
        migrations.RemoveField(
            model_name='executionhistory',
            name='group',
        ),
        migrations.RemoveField(
            model_name='executionhistory',
            name='host',
        ),
        migrations.RemoveField(
            model_name='executionhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='executed_on_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.group'),
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='executed_on_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.host'),
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
