# Generated by Django 5.1.2 on 2024-10-19 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0003_rename_date_executionhistory_execution_date_and_more'),
        ('inventory', '0003_delete_fingerprinthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_groups', to='inventory.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ansible_host', models.CharField(max_length=100)),
                ('ansible_user', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.group')),
            ],
        ),
    ]
