# Generated by Django 5.1.2 on 2024-10-19 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0004_group_host'),
        ('inventory', '0003_delete_fingerprinthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='group',
        ),
        migrations.RenameField(
            model_name='executionhistory',
            old_name='execution_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='executionhistory',
            old_name='user',
            new_name='executed_by',
        ),
        migrations.RenameField(
            model_name='executionhistory',
            old_name='executed_on_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='executionhistory',
            old_name='executed_on_host',
            new_name='host',
        ),
        migrations.RemoveField(
            model_name='executionhistory',
            name='success',
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.environment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executionhistory',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
