# Generated by Django 5.1.2 on 2024-10-24 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0006_alter_executionhistory_options'),
        ('inventory', '0003_delete_fingerprinthistory'),
        ('playbook', '0003_remove_playbook_system_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Executed', 'Executed'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('output', models.TextField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.environment')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.group')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.host')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbook.playbook')),
            ],
            options={
                'verbose_name': 'Scheduled Execution',
                'verbose_name_plural': 'Scheduled Executions',
            },
        ),
    ]
