# Generated by Django 5.1.2 on 2024-10-23 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_manager.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ansible_host', models.CharField(max_length=100)),
                ('ansible_user', models.CharField(default='root', max_length=50)),
                ('operating_system', models.CharField(choices=[('Redhat', 'Redhat'), ('Debian', 'Debian'), ('Windows', 'Windows')], max_length=50)),
                ('python_interpreter', models.CharField(default='/usr/bin/python3.12', max_length=100)),
                ('ssh_key', models.CharField(default='media/ssh_keys/id_rsa', max_length=255)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_manager.environment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_manager.group')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('start', 'Iniciar'), ('stop', 'Detener'), ('restart', 'Reiniciar'), ('status', 'Ver estado')], max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('output', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_manager.host')),
            ],
        ),
        migrations.CreateModel(
            name='SSHConnectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=255)),
                ('accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_manager.environment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_manager.group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_manager.host')),
            ],
        ),
    ]
