# Generated by Django 5.1.2 on 2024-10-23 20:57

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Variable')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.FileField(blank=True, null=True, upload_to=settings.models.upload_ssh_key_path, verbose_name='Llave privada')),
                ('public_key', models.FileField(blank=True, null=True, upload_to=settings.models.upload_ssh_key_path, verbose_name='Llave pública')),
            ],
        ),
    ]
