# Generated by Django 5.1.2 on 2024-10-17 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.environment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.host')),
            ],
        ),
    ]
