# Generated by Django 5.1.2 on 2024-10-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_fingerprinthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FingerprintHistory',
        ),
    ]
