# Generated by Django 5.1.2 on 2024-10-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('path', models.FileField(upload_to='playbooks/')),
                ('target_type', models.CharField(choices=[('Host', 'Host'), ('Group', 'Group')], max_length=10)),
                ('operating_system', models.CharField(choices=[('Redhat', 'Redhat'), ('Debian', 'Debian'), ('Windows', 'Windows')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
