# Generated by Django 5.1.2 on 2024-10-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='path',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='title',
        ),
        migrations.AddField(
            model_name='playbook',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playbook',
            name='playbook_file',
            field=models.FileField(default=1, upload_to='determine_upload_path'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playbook',
            name='system_type',
            field=models.CharField(choices=[('Redhat', 'Redhat'), ('Debian', 'Debian'), ('Windows', 'Windows')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playbook',
            name='target_type',
            field=models.CharField(choices=[('host', 'Host'), ('group', 'Group')], max_length=10),
        ),
    ]
