# Generated by Django 5.1.2 on 2024-10-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0002_remove_playbook_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='system_type',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='target_type',
        ),
        migrations.AddField(
            model_name='playbook',
            name='operating_system',
            field=models.CharField(choices=[('redhat', 'RedHat'), ('debian', 'Debian'), ('windows', 'Windows')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playbook',
            name='playbook_type',
            field=models.CharField(choices=[('group', 'Group'), ('host', 'Host')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playbook',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='playbook_file',
            field=models.FileField(upload_to='playbooks/'),
        ),
    ]
